# Generated by Django 3.0.5 on 2021-06-14 11:54

import core.models.point
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPost',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('area', models.TextField()),
                ('details', models.TextField()),
                ('item', models.TextField()),
                ('type', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('location', djongo.models.fields.EmbeddedField(model_container=core.models.point.Point)),
                ('person_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.TextField(default='Point')),
                ('coordinates', djongo.models.fields.JSONField()),
            ],
        ),
    ]
