# Generated by Django 3.0.5 on 2021-06-14 13:45

import core.models.point
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('area', models.TextField()),
                ('address', models.TextField()),
                ('location', djongo.models.fields.EmbeddedField(model_container=core.models.point.Point)),
            ],
        ),
    ]
