# Generated by Django 3.0.5 on 2021-06-14 14:25

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.TextField(default='Point')),
                ('coordinates', djongo.models.fields.JSONField()),
            ],
        ),
    ]
