# Generated by Django 3.0.5 on 2021-06-18 10:07

import core.models.essential
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essential',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('urls', djongo.models.fields.ArrayField(model_container=core.models.essential.State)),
            ],
        ),
        migrations.CreateModel(
            name='SingleUrlEssential',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
    ]
